### ISSUE TITLE
configure repository for Jenkins builds

### ISSUE THREAD

**Issue by ktdreyer** [ceph/jenkins-slave-chef#5]
Please set up the Jenkins service for this GitHub repository.
1. Go here: https://github.com/chef/jenkins-slave-chef/settings/hooks
2. Click "Add service" dropdown
3. Click the "Jenkins (GitHub plugin)" in the drop-down.
4. For Jenkins hook url, enter "http://jenkins.ceph.com/github-webhook".
5. Click the green "Add Service" button to save your changes.

As far as what Jenkins is going to do with this repository: there is a simple `rake` task that we'll use to sanity-check Ruby syntax errors. This is a really simple test that certainly won't catch everything, but at least it will build a bit of confidence when testing pull requests.

**Comment by ktdreyer** [comment]
Alternatively, you could put me in the "Owners" group in the ceph GitHub org and then I could make the change myself.

**Comment by dmick** [comment]
Confused...who is this to?

**Comment by ktdreyer** [comment]
I think I have to be in the "Owners" group in GitHub in order to make this level of change.

The current members of the "Owners" group are:
- liewegas
- athanatos
- SandonV
- dmick
- rossturk
- ircolle
- alfredodeza
- yehudasa
- dachary

So if one of you could put me in the Owners group (or else make this change itself) that would be great.

**Comment by dmick** [comment]
From the email alone, I couldn't tell this was an issue, and thought you were ... commenting to a pull request, or something?...
anyway, yes of course you can be an owner, and I can set up this hook as well.

**Comment by dmick** [comment]
Done.

**Comment by ktdreyer** [comment]
Cool, thanks Dan!
